### ISSUE TITLE
Doesn't show what speed increased

### ISSUE THREAD

**Issue by rnyPlanet** [IvanSavoskin/more-boosty-remaster#5]
![image](https://github.com/user-attachments/assets/e7de406f-d2e5-4667-a1bd-d174cbe4ef21)

Doesn't show what speed increased. 
it seemed to show how much speed it had increased for example “x3.5”

**Comment by IvanSavoskin** [comment]
Hi @rnyPlanet!
Thanks, I found the problem - it will be fixed in the next version

**Comment by IvanSavoskin** [comment]
Hi @rnyPlanet !
Fixed in the release https://github.com/IvanSavoskin/more-boosty-remaster/releases/tag/v1.0.0
I will also upload a new extension to Chrome WebStore soon.
Please check if the problem has been fixed for you.

**Comment by rnyPlanet** [comment]
Thank you. works as expected
